/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResidentesRouteImport } from './routes/residentes'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as ProspectosRouteImport } from './routes/prospectos'
import { Route as PropiedadesRouteImport } from './routes/propiedades'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PlanesRouteImport } from './routes/planes'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as MantenimientoRouteImport } from './routes/mantenimiento'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GuardiaRouteImport } from './routes/guardia'
import { Route as FinanzasRouteImport } from './routes/finanzas'
import { Route as EdificiosRouteImport } from './routes/edificios'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as ComunicacionesRouteImport } from './routes/comunicaciones'
import { Route as AreasRouteImport } from './routes/areas'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AdminPanelRouteImport } from './routes/admin-panel'
import { Route as AccesosRouteImport } from './routes/accesos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as GuardiaIndexRouteImport } from './routes/guardia.index'
import { Route as EdificiosIndexRouteImport } from './routes/edificios.index'
import { Route as AccesosIndexRouteImport } from './routes/accesos.index'
import { Route as ReciboCobroIdRouteImport } from './routes/recibo.$cobroId'
import { Route as PortalReservarRouteImport } from './routes/portal.reservar'
import { Route as PortalNuevoRouteImport } from './routes/portal.nuevo'
import { Route as PortalCuentaRouteImport } from './routes/portal.cuenta'
import { Route as PortalAnunciosRouteImport } from './routes/portal.anuncios'
import { Route as GuardiaTurnoRouteImport } from './routes/guardia.turno'
import { Route as GuardiaPasesRouteImport } from './routes/guardia.pases'
import { Route as EdificiosEdificioIdRouteImport } from './routes/edificios.$edificioId'
import { Route as AccesosValidarRouteImport } from './routes/accesos.validar'
import { Route as AccesosTurnosRouteImport } from './routes/accesos.turnos'
import { Route as AccesosPuntosRouteImport } from './routes/accesos.puntos'
import { Route as PortalPasePaseIdRouteImport } from './routes/portal.pase.$paseId'

const ResidentesRoute = ResidentesRouteImport.update({
  id: '/residentes',
  path: '/residentes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectosRoute = ProspectosRouteImport.update({
  id: '/prospectos',
  path: '/prospectos',
  getParentRoute: () => rootRouteImport,
} as any)
const PropiedadesRoute = PropiedadesRouteImport.update({
  id: '/propiedades',
  path: '/propiedades',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesRoute = PlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const MantenimientoRoute = MantenimientoRouteImport.update({
  id: '/mantenimiento',
  path: '/mantenimiento',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardiaRoute = GuardiaRouteImport.update({
  id: '/guardia',
  path: '/guardia',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanzasRoute = FinanzasRouteImport.update({
  id: '/finanzas',
  path: '/finanzas',
  getParentRoute: () => rootRouteImport,
} as any)
const EdificiosRoute = EdificiosRouteImport.update({
  id: '/edificios',
  path: '/edificios',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunicacionesRoute = ComunicacionesRouteImport.update({
  id: '/comunicaciones',
  path: '/comunicaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasRoute = AreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelRoute = AdminPanelRouteImport.update({
  id: '/admin-panel',
  path: '/admin-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesosRoute = AccesosRouteImport.update({
  id: '/accesos',
  path: '/accesos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const GuardiaIndexRoute = GuardiaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuardiaRoute,
} as any)
const EdificiosIndexRoute = EdificiosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EdificiosRoute,
} as any)
const AccesosIndexRoute = AccesosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccesosRoute,
} as any)
const ReciboCobroIdRoute = ReciboCobroIdRouteImport.update({
  id: '/recibo/$cobroId',
  path: '/recibo/$cobroId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalReservarRoute = PortalReservarRouteImport.update({
  id: '/reservar',
  path: '/reservar',
  getParentRoute: () => PortalRoute,
} as any)
const PortalNuevoRoute = PortalNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCuentaRoute = PortalCuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAnunciosRoute = PortalAnunciosRouteImport.update({
  id: '/anuncios',
  path: '/anuncios',
  getParentRoute: () => PortalRoute,
} as any)
const GuardiaTurnoRoute = GuardiaTurnoRouteImport.update({
  id: '/turno',
  path: '/turno',
  getParentRoute: () => GuardiaRoute,
} as any)
const GuardiaPasesRoute = GuardiaPasesRouteImport.update({
  id: '/pases',
  path: '/pases',
  getParentRoute: () => GuardiaRoute,
} as any)
const EdificiosEdificioIdRoute = EdificiosEdificioIdRouteImport.update({
  id: '/$edificioId',
  path: '/$edificioId',
  getParentRoute: () => EdificiosRoute,
} as any)
const AccesosValidarRoute = AccesosValidarRouteImport.update({
  id: '/validar',
  path: '/validar',
  getParentRoute: () => AccesosRoute,
} as any)
const AccesosTurnosRoute = AccesosTurnosRouteImport.update({
  id: '/turnos',
  path: '/turnos',
  getParentRoute: () => AccesosRoute,
} as any)
const AccesosPuntosRoute = AccesosPuntosRouteImport.update({
  id: '/puntos',
  path: '/puntos',
  getParentRoute: () => AccesosRoute,
} as any)
const PortalPasePaseIdRoute = PortalPasePaseIdRouteImport.update({
  id: '/pase/$paseId',
  path: '/pase/$paseId',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accesos': typeof AccesosRouteWithChildren
  '/admin-panel': typeof AdminPanelRoute
  '/agenda': typeof AgendaRoute
  '/areas': typeof AreasRoute
  '/comunicaciones': typeof ComunicacionesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/dashboard': typeof DashboardRoute
  '/edificios': typeof EdificiosRouteWithChildren
  '/finanzas': typeof FinanzasRoute
  '/guardia': typeof GuardiaRouteWithChildren
  '/login': typeof LoginRoute
  '/mantenimiento': typeof MantenimientoRoute
  '/pipeline': typeof PipelineRoute
  '/planes': typeof PlanesRoute
  '/portal': typeof PortalRouteWithChildren
  '/propiedades': typeof PropiedadesRoute
  '/prospectos': typeof ProspectosRoute
  '/reportes': typeof ReportesRoute
  '/residentes': typeof ResidentesRoute
  '/accesos/puntos': typeof AccesosPuntosRoute
  '/accesos/turnos': typeof AccesosTurnosRoute
  '/accesos/validar': typeof AccesosValidarRoute
  '/edificios/$edificioId': typeof EdificiosEdificioIdRoute
  '/guardia/pases': typeof GuardiaPasesRoute
  '/guardia/turno': typeof GuardiaTurnoRoute
  '/portal/anuncios': typeof PortalAnunciosRoute
  '/portal/cuenta': typeof PortalCuentaRoute
  '/portal/nuevo': typeof PortalNuevoRoute
  '/portal/reservar': typeof PortalReservarRoute
  '/recibo/$cobroId': typeof ReciboCobroIdRoute
  '/accesos/': typeof AccesosIndexRoute
  '/edificios/': typeof EdificiosIndexRoute
  '/guardia/': typeof GuardiaIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/pase/$paseId': typeof PortalPasePaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-panel': typeof AdminPanelRoute
  '/agenda': typeof AgendaRoute
  '/areas': typeof AreasRoute
  '/comunicaciones': typeof ComunicacionesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/dashboard': typeof DashboardRoute
  '/finanzas': typeof FinanzasRoute
  '/login': typeof LoginRoute
  '/mantenimiento': typeof MantenimientoRoute
  '/pipeline': typeof PipelineRoute
  '/planes': typeof PlanesRoute
  '/propiedades': typeof PropiedadesRoute
  '/prospectos': typeof ProspectosRoute
  '/reportes': typeof ReportesRoute
  '/residentes': typeof ResidentesRoute
  '/accesos/puntos': typeof AccesosPuntosRoute
  '/accesos/turnos': typeof AccesosTurnosRoute
  '/accesos/validar': typeof AccesosValidarRoute
  '/edificios/$edificioId': typeof EdificiosEdificioIdRoute
  '/guardia/pases': typeof GuardiaPasesRoute
  '/guardia/turno': typeof GuardiaTurnoRoute
  '/portal/anuncios': typeof PortalAnunciosRoute
  '/portal/cuenta': typeof PortalCuentaRoute
  '/portal/nuevo': typeof PortalNuevoRoute
  '/portal/reservar': typeof PortalReservarRoute
  '/recibo/$cobroId': typeof ReciboCobroIdRoute
  '/accesos': typeof AccesosIndexRoute
  '/edificios': typeof EdificiosIndexRoute
  '/guardia': typeof GuardiaIndexRoute
  '/portal': typeof PortalIndexRoute
  '/portal/pase/$paseId': typeof PortalPasePaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accesos': typeof AccesosRouteWithChildren
  '/admin-panel': typeof AdminPanelRoute
  '/agenda': typeof AgendaRoute
  '/areas': typeof AreasRoute
  '/comunicaciones': typeof ComunicacionesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/dashboard': typeof DashboardRoute
  '/edificios': typeof EdificiosRouteWithChildren
  '/finanzas': typeof FinanzasRoute
  '/guardia': typeof GuardiaRouteWithChildren
  '/login': typeof LoginRoute
  '/mantenimiento': typeof MantenimientoRoute
  '/pipeline': typeof PipelineRoute
  '/planes': typeof PlanesRoute
  '/portal': typeof PortalRouteWithChildren
  '/propiedades': typeof PropiedadesRoute
  '/prospectos': typeof ProspectosRoute
  '/reportes': typeof ReportesRoute
  '/residentes': typeof ResidentesRoute
  '/accesos/puntos': typeof AccesosPuntosRoute
  '/accesos/turnos': typeof AccesosTurnosRoute
  '/accesos/validar': typeof AccesosValidarRoute
  '/edificios/$edificioId': typeof EdificiosEdificioIdRoute
  '/guardia/pases': typeof GuardiaPasesRoute
  '/guardia/turno': typeof GuardiaTurnoRoute
  '/portal/anuncios': typeof PortalAnunciosRoute
  '/portal/cuenta': typeof PortalCuentaRoute
  '/portal/nuevo': typeof PortalNuevoRoute
  '/portal/reservar': typeof PortalReservarRoute
  '/recibo/$cobroId': typeof ReciboCobroIdRoute
  '/accesos/': typeof AccesosIndexRoute
  '/edificios/': typeof EdificiosIndexRoute
  '/guardia/': typeof GuardiaIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/pase/$paseId': typeof PortalPasePaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accesos'
    | '/admin-panel'
    | '/agenda'
    | '/areas'
    | '/comunicaciones'
    | '/configuracion'
    | '/dashboard'
    | '/edificios'
    | '/finanzas'
    | '/guardia'
    | '/login'
    | '/mantenimiento'
    | '/pipeline'
    | '/planes'
    | '/portal'
    | '/propiedades'
    | '/prospectos'
    | '/reportes'
    | '/residentes'
    | '/accesos/puntos'
    | '/accesos/turnos'
    | '/accesos/validar'
    | '/edificios/$edificioId'
    | '/guardia/pases'
    | '/guardia/turno'
    | '/portal/anuncios'
    | '/portal/cuenta'
    | '/portal/nuevo'
    | '/portal/reservar'
    | '/recibo/$cobroId'
    | '/accesos/'
    | '/edificios/'
    | '/guardia/'
    | '/portal/'
    | '/portal/pase/$paseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-panel'
    | '/agenda'
    | '/areas'
    | '/comunicaciones'
    | '/configuracion'
    | '/dashboard'
    | '/finanzas'
    | '/login'
    | '/mantenimiento'
    | '/pipeline'
    | '/planes'
    | '/propiedades'
    | '/prospectos'
    | '/reportes'
    | '/residentes'
    | '/accesos/puntos'
    | '/accesos/turnos'
    | '/accesos/validar'
    | '/edificios/$edificioId'
    | '/guardia/pases'
    | '/guardia/turno'
    | '/portal/anuncios'
    | '/portal/cuenta'
    | '/portal/nuevo'
    | '/portal/reservar'
    | '/recibo/$cobroId'
    | '/accesos'
    | '/edificios'
    | '/guardia'
    | '/portal'
    | '/portal/pase/$paseId'
  id:
    | '__root__'
    | '/'
    | '/accesos'
    | '/admin-panel'
    | '/agenda'
    | '/areas'
    | '/comunicaciones'
    | '/configuracion'
    | '/dashboard'
    | '/edificios'
    | '/finanzas'
    | '/guardia'
    | '/login'
    | '/mantenimiento'
    | '/pipeline'
    | '/planes'
    | '/portal'
    | '/propiedades'
    | '/prospectos'
    | '/reportes'
    | '/residentes'
    | '/accesos/puntos'
    | '/accesos/turnos'
    | '/accesos/validar'
    | '/edificios/$edificioId'
    | '/guardia/pases'
    | '/guardia/turno'
    | '/portal/anuncios'
    | '/portal/cuenta'
    | '/portal/nuevo'
    | '/portal/reservar'
    | '/recibo/$cobroId'
    | '/accesos/'
    | '/edificios/'
    | '/guardia/'
    | '/portal/'
    | '/portal/pase/$paseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccesosRoute: typeof AccesosRouteWithChildren
  AdminPanelRoute: typeof AdminPanelRoute
  AgendaRoute: typeof AgendaRoute
  AreasRoute: typeof AreasRoute
  ComunicacionesRoute: typeof ComunicacionesRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  DashboardRoute: typeof DashboardRoute
  EdificiosRoute: typeof EdificiosRouteWithChildren
  FinanzasRoute: typeof FinanzasRoute
  GuardiaRoute: typeof GuardiaRouteWithChildren
  LoginRoute: typeof LoginRoute
  MantenimientoRoute: typeof MantenimientoRoute
  PipelineRoute: typeof PipelineRoute
  PlanesRoute: typeof PlanesRoute
  PortalRoute: typeof PortalRouteWithChildren
  PropiedadesRoute: typeof PropiedadesRoute
  ProspectosRoute: typeof ProspectosRoute
  ReportesRoute: typeof ReportesRoute
  ResidentesRoute: typeof ResidentesRoute
  ReciboCobroIdRoute: typeof ReciboCobroIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/residentes': {
      id: '/residentes'
      path: '/residentes'
      fullPath: '/residentes'
      preLoaderRoute: typeof ResidentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospectos': {
      id: '/prospectos'
      path: '/prospectos'
      fullPath: '/prospectos'
      preLoaderRoute: typeof ProspectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propiedades': {
      id: '/propiedades'
      path: '/propiedades'
      fullPath: '/propiedades'
      preLoaderRoute: typeof PropiedadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes': {
      id: '/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mantenimiento': {
      id: '/mantenimiento'
      path: '/mantenimiento'
      fullPath: '/mantenimiento'
      preLoaderRoute: typeof MantenimientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardia': {
      id: '/guardia'
      path: '/guardia'
      fullPath: '/guardia'
      preLoaderRoute: typeof GuardiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finanzas': {
      id: '/finanzas'
      path: '/finanzas'
      fullPath: '/finanzas'
      preLoaderRoute: typeof FinanzasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edificios': {
      id: '/edificios'
      path: '/edificios'
      fullPath: '/edificios'
      preLoaderRoute: typeof EdificiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunicaciones': {
      id: '/comunicaciones'
      path: '/comunicaciones'
      fullPath: '/comunicaciones'
      preLoaderRoute: typeof ComunicacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas': {
      id: '/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-panel': {
      id: '/admin-panel'
      path: '/admin-panel'
      fullPath: '/admin-panel'
      preLoaderRoute: typeof AdminPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accesos': {
      id: '/accesos'
      path: '/accesos'
      fullPath: '/accesos'
      preLoaderRoute: typeof AccesosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/guardia/': {
      id: '/guardia/'
      path: '/'
      fullPath: '/guardia/'
      preLoaderRoute: typeof GuardiaIndexRouteImport
      parentRoute: typeof GuardiaRoute
    }
    '/edificios/': {
      id: '/edificios/'
      path: '/'
      fullPath: '/edificios/'
      preLoaderRoute: typeof EdificiosIndexRouteImport
      parentRoute: typeof EdificiosRoute
    }
    '/accesos/': {
      id: '/accesos/'
      path: '/'
      fullPath: '/accesos/'
      preLoaderRoute: typeof AccesosIndexRouteImport
      parentRoute: typeof AccesosRoute
    }
    '/recibo/$cobroId': {
      id: '/recibo/$cobroId'
      path: '/recibo/$cobroId'
      fullPath: '/recibo/$cobroId'
      preLoaderRoute: typeof ReciboCobroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/reservar': {
      id: '/portal/reservar'
      path: '/reservar'
      fullPath: '/portal/reservar'
      preLoaderRoute: typeof PortalReservarRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/nuevo': {
      id: '/portal/nuevo'
      path: '/nuevo'
      fullPath: '/portal/nuevo'
      preLoaderRoute: typeof PortalNuevoRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/cuenta': {
      id: '/portal/cuenta'
      path: '/cuenta'
      fullPath: '/portal/cuenta'
      preLoaderRoute: typeof PortalCuentaRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/anuncios': {
      id: '/portal/anuncios'
      path: '/anuncios'
      fullPath: '/portal/anuncios'
      preLoaderRoute: typeof PortalAnunciosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/guardia/turno': {
      id: '/guardia/turno'
      path: '/turno'
      fullPath: '/guardia/turno'
      preLoaderRoute: typeof GuardiaTurnoRouteImport
      parentRoute: typeof GuardiaRoute
    }
    '/guardia/pases': {
      id: '/guardia/pases'
      path: '/pases'
      fullPath: '/guardia/pases'
      preLoaderRoute: typeof GuardiaPasesRouteImport
      parentRoute: typeof GuardiaRoute
    }
    '/edificios/$edificioId': {
      id: '/edificios/$edificioId'
      path: '/$edificioId'
      fullPath: '/edificios/$edificioId'
      preLoaderRoute: typeof EdificiosEdificioIdRouteImport
      parentRoute: typeof EdificiosRoute
    }
    '/accesos/validar': {
      id: '/accesos/validar'
      path: '/validar'
      fullPath: '/accesos/validar'
      preLoaderRoute: typeof AccesosValidarRouteImport
      parentRoute: typeof AccesosRoute
    }
    '/accesos/turnos': {
      id: '/accesos/turnos'
      path: '/turnos'
      fullPath: '/accesos/turnos'
      preLoaderRoute: typeof AccesosTurnosRouteImport
      parentRoute: typeof AccesosRoute
    }
    '/accesos/puntos': {
      id: '/accesos/puntos'
      path: '/puntos'
      fullPath: '/accesos/puntos'
      preLoaderRoute: typeof AccesosPuntosRouteImport
      parentRoute: typeof AccesosRoute
    }
    '/portal/pase/$paseId': {
      id: '/portal/pase/$paseId'
      path: '/pase/$paseId'
      fullPath: '/portal/pase/$paseId'
      preLoaderRoute: typeof PortalPasePaseIdRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface AccesosRouteChildren {
  AccesosPuntosRoute: typeof AccesosPuntosRoute
  AccesosTurnosRoute: typeof AccesosTurnosRoute
  AccesosValidarRoute: typeof AccesosValidarRoute
  AccesosIndexRoute: typeof AccesosIndexRoute
}

const AccesosRouteChildren: AccesosRouteChildren = {
  AccesosPuntosRoute: AccesosPuntosRoute,
  AccesosTurnosRoute: AccesosTurnosRoute,
  AccesosValidarRoute: AccesosValidarRoute,
  AccesosIndexRoute: AccesosIndexRoute,
}

const AccesosRouteWithChildren =
  AccesosRoute._addFileChildren(AccesosRouteChildren)

interface EdificiosRouteChildren {
  EdificiosEdificioIdRoute: typeof EdificiosEdificioIdRoute
  EdificiosIndexRoute: typeof EdificiosIndexRoute
}

const EdificiosRouteChildren: EdificiosRouteChildren = {
  EdificiosEdificioIdRoute: EdificiosEdificioIdRoute,
  EdificiosIndexRoute: EdificiosIndexRoute,
}

const EdificiosRouteWithChildren = EdificiosRoute._addFileChildren(
  EdificiosRouteChildren,
)

interface GuardiaRouteChildren {
  GuardiaPasesRoute: typeof GuardiaPasesRoute
  GuardiaTurnoRoute: typeof GuardiaTurnoRoute
  GuardiaIndexRoute: typeof GuardiaIndexRoute
}

const GuardiaRouteChildren: GuardiaRouteChildren = {
  GuardiaPasesRoute: GuardiaPasesRoute,
  GuardiaTurnoRoute: GuardiaTurnoRoute,
  GuardiaIndexRoute: GuardiaIndexRoute,
}

const GuardiaRouteWithChildren =
  GuardiaRoute._addFileChildren(GuardiaRouteChildren)

interface PortalRouteChildren {
  PortalAnunciosRoute: typeof PortalAnunciosRoute
  PortalCuentaRoute: typeof PortalCuentaRoute
  PortalNuevoRoute: typeof PortalNuevoRoute
  PortalReservarRoute: typeof PortalReservarRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalPasePaseIdRoute: typeof PortalPasePaseIdRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAnunciosRoute: PortalAnunciosRoute,
  PortalCuentaRoute: PortalCuentaRoute,
  PortalNuevoRoute: PortalNuevoRoute,
  PortalReservarRoute: PortalReservarRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalPasePaseIdRoute: PortalPasePaseIdRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccesosRoute: AccesosRouteWithChildren,
  AdminPanelRoute: AdminPanelRoute,
  AgendaRoute: AgendaRoute,
  AreasRoute: AreasRoute,
  ComunicacionesRoute: ComunicacionesRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  DashboardRoute: DashboardRoute,
  EdificiosRoute: EdificiosRouteWithChildren,
  FinanzasRoute: FinanzasRoute,
  GuardiaRoute: GuardiaRouteWithChildren,
  LoginRoute: LoginRoute,
  MantenimientoRoute: MantenimientoRoute,
  PipelineRoute: PipelineRoute,
  PlanesRoute: PlanesRoute,
  PortalRoute: PortalRouteWithChildren,
  PropiedadesRoute: PropiedadesRoute,
  ProspectosRoute: ProspectosRoute,
  ReportesRoute: ReportesRoute,
  ResidentesRoute: ResidentesRoute,
  ReciboCobroIdRoute: ReciboCobroIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
