/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResidentesRouteImport } from './routes/residentes'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as ProspectosRouteImport } from './routes/prospectos'
import { Route as PropiedadesRouteImport } from './routes/propiedades'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as MantenimientoRouteImport } from './routes/mantenimiento'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FinanzasRouteImport } from './routes/finanzas'
import { Route as EdificiosRouteImport } from './routes/edificios'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as ComunicacionesRouteImport } from './routes/comunicaciones'
import { Route as AreasRouteImport } from './routes/areas'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AccesosRouteImport } from './routes/accesos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EdificiosIndexRouteImport } from './routes/edificios.index'
import { Route as ReciboCobroIdRouteImport } from './routes/recibo.$cobroId'
import { Route as EdificiosEdificioIdRouteImport } from './routes/edificios.$edificioId'
import { Route as AccesosValidarRouteImport } from './routes/accesos.validar'

const ResidentesRoute = ResidentesRouteImport.update({
  id: '/residentes',
  path: '/residentes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectosRoute = ProspectosRouteImport.update({
  id: '/prospectos',
  path: '/prospectos',
  getParentRoute: () => rootRouteImport,
} as any)
const PropiedadesRoute = PropiedadesRouteImport.update({
  id: '/propiedades',
  path: '/propiedades',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const MantenimientoRoute = MantenimientoRouteImport.update({
  id: '/mantenimiento',
  path: '/mantenimiento',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanzasRoute = FinanzasRouteImport.update({
  id: '/finanzas',
  path: '/finanzas',
  getParentRoute: () => rootRouteImport,
} as any)
const EdificiosRoute = EdificiosRouteImport.update({
  id: '/edificios',
  path: '/edificios',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunicacionesRoute = ComunicacionesRouteImport.update({
  id: '/comunicaciones',
  path: '/comunicaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasRoute = AreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesosRoute = AccesosRouteImport.update({
  id: '/accesos',
  path: '/accesos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EdificiosIndexRoute = EdificiosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EdificiosRoute,
} as any)
const ReciboCobroIdRoute = ReciboCobroIdRouteImport.update({
  id: '/recibo/$cobroId',
  path: '/recibo/$cobroId',
  getParentRoute: () => rootRouteImport,
} as any)
const EdificiosEdificioIdRoute = EdificiosEdificioIdRouteImport.update({
  id: '/$edificioId',
  path: '/$edificioId',
  getParentRoute: () => EdificiosRoute,
} as any)
const AccesosValidarRoute = AccesosValidarRouteImport.update({
  id: '/validar',
  path: '/validar',
  getParentRoute: () => AccesosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accesos': typeof AccesosRouteWithChildren
  '/agenda': typeof AgendaRoute
  '/areas': typeof AreasRoute
  '/comunicaciones': typeof ComunicacionesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/edificios': typeof EdificiosRouteWithChildren
  '/finanzas': typeof FinanzasRoute
  '/login': typeof LoginRoute
  '/mantenimiento': typeof MantenimientoRoute
  '/pipeline': typeof PipelineRoute
  '/propiedades': typeof PropiedadesRoute
  '/prospectos': typeof ProspectosRoute
  '/reportes': typeof ReportesRoute
  '/residentes': typeof ResidentesRoute
  '/accesos/validar': typeof AccesosValidarRoute
  '/edificios/$edificioId': typeof EdificiosEdificioIdRoute
  '/recibo/$cobroId': typeof ReciboCobroIdRoute
  '/edificios/': typeof EdificiosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accesos': typeof AccesosRouteWithChildren
  '/agenda': typeof AgendaRoute
  '/areas': typeof AreasRoute
  '/comunicaciones': typeof ComunicacionesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/finanzas': typeof FinanzasRoute
  '/login': typeof LoginRoute
  '/mantenimiento': typeof MantenimientoRoute
  '/pipeline': typeof PipelineRoute
  '/propiedades': typeof PropiedadesRoute
  '/prospectos': typeof ProspectosRoute
  '/reportes': typeof ReportesRoute
  '/residentes': typeof ResidentesRoute
  '/accesos/validar': typeof AccesosValidarRoute
  '/edificios/$edificioId': typeof EdificiosEdificioIdRoute
  '/recibo/$cobroId': typeof ReciboCobroIdRoute
  '/edificios': typeof EdificiosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accesos': typeof AccesosRouteWithChildren
  '/agenda': typeof AgendaRoute
  '/areas': typeof AreasRoute
  '/comunicaciones': typeof ComunicacionesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/edificios': typeof EdificiosRouteWithChildren
  '/finanzas': typeof FinanzasRoute
  '/login': typeof LoginRoute
  '/mantenimiento': typeof MantenimientoRoute
  '/pipeline': typeof PipelineRoute
  '/propiedades': typeof PropiedadesRoute
  '/prospectos': typeof ProspectosRoute
  '/reportes': typeof ReportesRoute
  '/residentes': typeof ResidentesRoute
  '/accesos/validar': typeof AccesosValidarRoute
  '/edificios/$edificioId': typeof EdificiosEdificioIdRoute
  '/recibo/$cobroId': typeof ReciboCobroIdRoute
  '/edificios/': typeof EdificiosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accesos'
    | '/agenda'
    | '/areas'
    | '/comunicaciones'
    | '/configuracion'
    | '/edificios'
    | '/finanzas'
    | '/login'
    | '/mantenimiento'
    | '/pipeline'
    | '/propiedades'
    | '/prospectos'
    | '/reportes'
    | '/residentes'
    | '/accesos/validar'
    | '/edificios/$edificioId'
    | '/recibo/$cobroId'
    | '/edificios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accesos'
    | '/agenda'
    | '/areas'
    | '/comunicaciones'
    | '/configuracion'
    | '/finanzas'
    | '/login'
    | '/mantenimiento'
    | '/pipeline'
    | '/propiedades'
    | '/prospectos'
    | '/reportes'
    | '/residentes'
    | '/accesos/validar'
    | '/edificios/$edificioId'
    | '/recibo/$cobroId'
    | '/edificios'
  id:
    | '__root__'
    | '/'
    | '/accesos'
    | '/agenda'
    | '/areas'
    | '/comunicaciones'
    | '/configuracion'
    | '/edificios'
    | '/finanzas'
    | '/login'
    | '/mantenimiento'
    | '/pipeline'
    | '/propiedades'
    | '/prospectos'
    | '/reportes'
    | '/residentes'
    | '/accesos/validar'
    | '/edificios/$edificioId'
    | '/recibo/$cobroId'
    | '/edificios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccesosRoute: typeof AccesosRouteWithChildren
  AgendaRoute: typeof AgendaRoute
  AreasRoute: typeof AreasRoute
  ComunicacionesRoute: typeof ComunicacionesRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  EdificiosRoute: typeof EdificiosRouteWithChildren
  FinanzasRoute: typeof FinanzasRoute
  LoginRoute: typeof LoginRoute
  MantenimientoRoute: typeof MantenimientoRoute
  PipelineRoute: typeof PipelineRoute
  PropiedadesRoute: typeof PropiedadesRoute
  ProspectosRoute: typeof ProspectosRoute
  ReportesRoute: typeof ReportesRoute
  ResidentesRoute: typeof ResidentesRoute
  ReciboCobroIdRoute: typeof ReciboCobroIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/residentes': {
      id: '/residentes'
      path: '/residentes'
      fullPath: '/residentes'
      preLoaderRoute: typeof ResidentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospectos': {
      id: '/prospectos'
      path: '/prospectos'
      fullPath: '/prospectos'
      preLoaderRoute: typeof ProspectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propiedades': {
      id: '/propiedades'
      path: '/propiedades'
      fullPath: '/propiedades'
      preLoaderRoute: typeof PropiedadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mantenimiento': {
      id: '/mantenimiento'
      path: '/mantenimiento'
      fullPath: '/mantenimiento'
      preLoaderRoute: typeof MantenimientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finanzas': {
      id: '/finanzas'
      path: '/finanzas'
      fullPath: '/finanzas'
      preLoaderRoute: typeof FinanzasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edificios': {
      id: '/edificios'
      path: '/edificios'
      fullPath: '/edificios'
      preLoaderRoute: typeof EdificiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunicaciones': {
      id: '/comunicaciones'
      path: '/comunicaciones'
      fullPath: '/comunicaciones'
      preLoaderRoute: typeof ComunicacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas': {
      id: '/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accesos': {
      id: '/accesos'
      path: '/accesos'
      fullPath: '/accesos'
      preLoaderRoute: typeof AccesosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edificios/': {
      id: '/edificios/'
      path: '/'
      fullPath: '/edificios/'
      preLoaderRoute: typeof EdificiosIndexRouteImport
      parentRoute: typeof EdificiosRoute
    }
    '/recibo/$cobroId': {
      id: '/recibo/$cobroId'
      path: '/recibo/$cobroId'
      fullPath: '/recibo/$cobroId'
      preLoaderRoute: typeof ReciboCobroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edificios/$edificioId': {
      id: '/edificios/$edificioId'
      path: '/$edificioId'
      fullPath: '/edificios/$edificioId'
      preLoaderRoute: typeof EdificiosEdificioIdRouteImport
      parentRoute: typeof EdificiosRoute
    }
    '/accesos/validar': {
      id: '/accesos/validar'
      path: '/validar'
      fullPath: '/accesos/validar'
      preLoaderRoute: typeof AccesosValidarRouteImport
      parentRoute: typeof AccesosRoute
    }
  }
}

interface AccesosRouteChildren {
  AccesosValidarRoute: typeof AccesosValidarRoute
}

const AccesosRouteChildren: AccesosRouteChildren = {
  AccesosValidarRoute: AccesosValidarRoute,
}

const AccesosRouteWithChildren =
  AccesosRoute._addFileChildren(AccesosRouteChildren)

interface EdificiosRouteChildren {
  EdificiosEdificioIdRoute: typeof EdificiosEdificioIdRoute
  EdificiosIndexRoute: typeof EdificiosIndexRoute
}

const EdificiosRouteChildren: EdificiosRouteChildren = {
  EdificiosEdificioIdRoute: EdificiosEdificioIdRoute,
  EdificiosIndexRoute: EdificiosIndexRoute,
}

const EdificiosRouteWithChildren = EdificiosRoute._addFileChildren(
  EdificiosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccesosRoute: AccesosRouteWithChildren,
  AgendaRoute: AgendaRoute,
  AreasRoute: AreasRoute,
  ComunicacionesRoute: ComunicacionesRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  EdificiosRoute: EdificiosRouteWithChildren,
  FinanzasRoute: FinanzasRoute,
  LoginRoute: LoginRoute,
  MantenimientoRoute: MantenimientoRoute,
  PipelineRoute: PipelineRoute,
  PropiedadesRoute: PropiedadesRoute,
  ProspectosRoute: ProspectosRoute,
  ReportesRoute: ReportesRoute,
  ResidentesRoute: ResidentesRoute,
  ReciboCobroIdRoute: ReciboCobroIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
